### ISSUE TITLE
Aptik v17.3 open web links as root

### ISSUE THREAD

**Issue by eson57** [teejee2008/aptik-legacy#3]
Checking the latest release, I found that the application tries to open web site, issue tracker, donation sites etc. as root. It also seems to ignore my default browser (firefox), using chromium instead.

![2017-03-31_10-50-32](https://cloud.githubusercontent.com/assets/2996154/24543849/5c6658e4-1601-11e7-9e88-6a5ef6f226c3.png)

**Comment by teejee2008** [comment]
Fixed in v17.3.1

**Comment by eson57** [comment]
Thanks! You forgot the http://teejeetech.in and others @ About Page.
Swedish gui translation also seems to be forgotten.

**Comment by teejee2008** [comment]
Will fix later. Thanks for mentioning :-)

**Comment by teejee2008** [comment]
Fixed in v17.4. Swedish translation was also added.

**Comment by eson57** [comment]
👍  :)
